modulo-11-desenvolvimento-blog/blog/config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  devise_for :users
  
  # /posts/1/comments/2
  resources :posts do
    resources :comments
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  # Formas de criar uma rota
  get "home", controller: "home", action: :index
  get "home2", to: "home#index"
  get "estudantes", to: "estudantes#index"
end

modulo-11-desenvolvimento-blog/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

modulo-11-desenvolvimento-blog/blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  # habilita rich text (texto rico) no Rails usando o Action Text, um recurso introduzido no Rails 6
  has_rich_text :body
end

modulo-11-desenvolvimento-blog/blog/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  # quando o post for excluído, os comentários tbm serão
  has_many :comments, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    %w[title body user_email] # lista de atributos permitidos para pesquisa do ransack
  end

  def self.ransackable_associations(auth_object = nil)
    ['user'] # permitindo a associação 'user' para pesquisa do ransack
  end
end

modulo-11-desenvolvimento-blog/blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # dependent: :destroy  = quando o usuário for excluído, os comentários e posts tbm serão
  has_many :posts, dependent: :destroy 
  has_many :comments, dependent: :destroy 
end

modulo-11-desenvolvimento-blog/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_query

  def set_query
    @query = Post.ransack(params[:q])
  end
end

modulo-11-desenvolvimento-blog/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user

    if @comment.save
        flash[:notice] = "Comentário criado com sucesso"
        redirect_to post_path(@post)
    else
      flash[:alert] = "Comentário não foi criado"
      redirect_to post_path(@post)
    end
  end

  def update
    @comment = @post.comments.find(params[:id])

    respond_to do |format|
      if @comment.update(comment_params)
        format.html{ redirect_to post_url(@post), notice: "Comentário atualizado" }
      else
        format.html{ redirect_to post_url(@post), notice: "Erro na atualização" }
      end
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

    def set_post
      @post = Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
end

modulo-11-desenvolvimento-blog/blog/app/controllers/estudantes_controller.rb
class EstudantesController < ApplicationController
  def index
    @estudantes = [
      {nome: "Aluno 1", idade: 19, curso: "Direito"},
      {nome: "Aluno 2", idade: 20, curso: "Computação"},
      {nome: "Aluno 3", idade: 21, curso: "Engenharia"},
    ]
  end
end

modulo-11-desenvolvimento-blog/blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @msg = 'Olá mundo' # @ = variável de instância
    # render html: "<h2>Olá mundo</h2>".html_safe
    # render html: "<h2>#{@msg}</h2>".html_safe

    @name = "Rodrigo"
    @posts = [
      {title: "Rails", body: "Aprendendo com a OBC"},
      {title: "Javascript", body: "Aprendendo com a OBC"},
      {title: "Python", body: "Aprendendo com a OBC"},
    ]
  end
end

modulo-11-desenvolvimento-blog/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index] # verifica se o usuário esta autenticado
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    # sempre que acessar o metodo, aumenta uma visualização
    # o método .to_i, que já transforma nil em 0
    @post.update(views: @post.views.to_i + 1)
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

modulo-11-desenvolvimento-blog/blog/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Post.ransack(params[:q])
    @posts = @query.result(distinct: true)
  end
end

modulo-11-desenvolvimento-blog/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

modulo-11-desenvolvimento-blog/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

modulo-11-desenvolvimento-blog/blog/app/helpers/posts_helper.rb
module PostsHelper
end

modulo-11-desenvolvimento-blog/blog/app/helpers/search_helper.rb
module SearchHelper
end

modulo-11-desenvolvimento-blog/blog/app/views/comments/_form.html.erb
<%= form_with(model: [post, comment]) do |f| %>
  <div class="form-control">
    <%= f.rich_text_area :body %>
    <%= f.submit submit_label, class: "btn btn-primary mt-1" %>
  </div>
<% end %>

modulo-11-desenvolvimento-blog/blog/app/views/estudantes/index.html.erb
<div class="container">
  <h2 style="text-align: center;">Informações dos Estudantes</h2>
  <hr>
  <div class="accordion" id="accordionExample">
    <% @estudantes.each_with_index do |estudante, index| %>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne<%= index %>">
          <button
            class="accordion-button"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapse<%= index %>"
            aria-expanded="true"
            aria-controls="collapseOne<%= index %>"
          >
            <%= estudante[:nome] %>
          </button>
        </h2>
        <div
          id="collapse<%= index %>"
          class="accordion-collapse collapse show" 
          aria-labelledby="headingOne<%= index %>"
          data-bs-parent="#accordionExample"
        >
          <div class="accordion-body">
            <p><%= estudante[:idade] %> anos</p>
            <p><%= estudante[:curso] %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>


  <%= link_to "Home", home_path %> <%# <a href="/home">Home</a> %>
</div>

modulo-11-desenvolvimento-blog/blog/app/views/home/index.html.erb
<div class="container">
  <h1>Blog Pessoal</h1>
  <p>Para conferir meus posts, clique no link a seguir:</p>
  <%= link_to "Blog", posts_path, class: "btn btn-primary" %>
</div>

modulo-11-desenvolvimento-blog/blog/app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

modulo-11-desenvolvimento-blog/blog/app/views/posts/_comment.html.erb
<div
  id="comment-<%= comment.id %>"
  style="border: 1px solid black; padding: 1 em; margin: 1em;"
>
  <%= comment.user.email %>
  <br />

  <% if (comment.updated_at - comment.created_at) > 1 %>
    <span>Editado: <%= time_ago_in_words(comment.updated_at) %></span>
  <% else %>
    <span>Postado: <%= time_ago_in_words(comment.created_at) %></span>
  <% end %>
  
  <% if current_user == comment.user %>
    <div class="btn-group float-end">
      <%= link_to "Edit",
        nil,
        remote: true,
        class: "btn btn-warning",
        data: {
          controller: "comments",
          action: "comments#toggleForm",
          comments_form_param: "edit-form-#{comment.id}",
          comments_body_param: "comment-body-#{comment.id}"
        }
      %>
      <%= button_to "Delete", [post, comment], class:"btn btn-danger", method: :delete%>
    </div>
  <% end %>
  
  <div id="edit-form-<%= comment.id %>" class="d-none">
    <%= render "comments/form", post: @post, comment: comment, submit_label: "Update" %>
  </div>
  
  <hr>
  
  <div id="comment-body-<%= comment.id %>" class="d-none">
    <%= comment.body %>
  </div>
</div>

modulo-11-desenvolvimento-blog/blog/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

modulo-11-desenvolvimento-blog/blog/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
    <p><%= pluralize(post.views, "view") %></p>
    <p>publicado por: <%= post.user.email %></p>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

modulo-11-desenvolvimento-blog/blog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

modulo-11-desenvolvimento-blog/blog/app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

modulo-11-desenvolvimento-blog/blog/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

modulo-11-desenvolvimento-blog/blog/app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

<br>

<%= render "comments/form", post: @post, comment: @post.comments.build, submit_label: "Reply" %>

<% @comments.each do |comment| %>
  <%= render "comment", post: @post, comment: comment %>
<% end %>

modulo-11-desenvolvimento-blog/blog/app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get, class:"d-flex") do |f| %>
  <%= f.search_field :title_or_body_or_user_email_i_cont_any, placeholder: "Search", class: "form-control me-2" %>
  <%= f.submit "Pesquisar", class: "btn btn-outline-success" %>
<% end %>

modulo-11-desenvolvimento-blog/blog/app/views/search/index.html.erb
<h1 class="text-center">
  <%= pluralize(@posts.count, "result") %>
</h1>

<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= sort_link(@query, :title, "Title", default_order: :asc) %></th>
        <th><%= sort_link(@query, :body, "Content") %></th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.title, post %></td>
          <td><%= post.body.truncate_words(25) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

modulo-11-desenvolvimento-blog/blog/app/views/user/_session.html.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Gerenciamento Usuário
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
      <li><%= link_to "Novo Post", new_post_path, class: "dropdown-item" %></li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <a class="dropdown-item" href="#"></a>
        <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
      </li>
    </ul>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to "Cadastro", new_user_registration_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Login", new_user_session_path, class: "nav-link" %>
  </li>
<% end %>